# Generated by Django 2.2.13 on 2020-06-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200619_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='jhtjhgjhg',
        ),
    ]
